# theme.toml template for a Hugo theme
name = "Roxo Hugo"
license = "MIT"
description = "Theme"
tags = ['clean', 'minimal']
features = ['bootstrap 4', 'responsive design', 'blog', 'responsive','landing-page', 'minimal', 'business', 'agency-template', 'hugo-theme', 'portfolio', 'company', 'creative', 'contact-form']
min_version = "0.58.0"


